name: flutter_dev_panel_console
description: Console/Logs module for Flutter Dev Panel
version: 0.0.2
homepage: https://github.com/royorange/flutter_dev_panel

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_dev_panel:
    path: ../..
  
  intl: ^0.19.0
  
  # Optional dependency for Logger integration
  # Users who use Logger already have this, so no extra download
  logger: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.25.0

flutter: