name: flutter_dev_panel_network
description: Network monitoring module for Flutter Dev Panel
version: 1.0.1
homepage: https://github.com/royorange/flutter-dev-panel

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dev_panel:
    path: ../..
  dio: ^5.4.0
  http: ^1.2.0
  graphql_flutter: ^5.1.0
  gql: ^1.0.0
  intl: ^0.19.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.0

flutter:
