name: flutter_dev_panel_performance
description: Performance monitoring module for Flutter Dev Panel
version: 0.0.1
homepage: https://github.com/royorange/flutter-dev-panel

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dev_panel_core:
    path: ../flutter_dev_panel_core
  fl_chart: ^0.68.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
