name: flutter_dev_panel_performance
description: Performance monitoring module for Flutter Dev Panel
version: 1.0.1
homepage: https://github.com/royorange/flutter-dev-panel

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dev_panel:
    path: ../..
  fl_chart: ^0.68.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.0

flutter:
